apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.database.pvcclaim_name}}
  annotations:
    pvc/dest: {{.Values.database.pvcclaim_destination | quote}}
spec: 
  accessModes:
    - {{.Values.database.pvcclaim_accessmode}}
  storageClassName: {{.Values.database.storageclass_name}}
  resources: 
    requests:
      storage: {{.Values.database.pvcclaim_request_storage}}