apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{.Values.hpa_app.name}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Values.deployment_app.deployment_name}}
  minReplicas: {{.Values.hpa_app.min_replicas}}
  maxReplicas: {{.Values.hpa_app.max_replicas}}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{.Values.hpa_app.cpu_average_utilization}}

