apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
  namespace: default
spec:
  project: default
  source:
    repoURL:  https://github.com/Jcobzajac/GitOps.git
    targetRevision: HEAD
    path: apps/charts/application
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: True
      selfHeal: True
    syncOptions:
      - CreateNamespace=true

