apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.ingress_controller.servacc_name}}
  namespace: {{.Values.ingress_controller.namespace}}
  annotations:
    eks.amazonaws.com/role-arn: {{.Values.ingress_controller.servcacc_rolearn}}