apiVersion: v1
kind: Service
metadata:
  name: {{.Values.ingress_controller.service_name}}
spec:
  ports:
  - port: {{.Values.ingress_controller.service_port}}
    targetPort: {{.Values.ingress_controller.service_targetport}}
    protocol: {{.Values.ingress_controller.service_protocol}}
  type: {{.Values.ingress_controller.service_type}}
  selector:
    app: {{.Values.deployment_app.container_label_value}}